version: "3.8"

services:
  rabbit-1:
    hostname: rabbit-1
    # container_name: rabbit-1
    image: rabbitmq:3.11.3-management
    ports:
      - "5672:5672"
      - "8101:15672"
      # - "5672:5672"
      # - "15672:15672"
      # - "15691:15691"
      # - "15692:15692"
    volumes:
      - "/srv/rabbitmq/config/rabbit-1/:/config/"
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE="YYRDITCRAERCUROGWFMZ"
    deploy:
      replicas: 3
      placement:
        constraints:
          # - "node.role==worker"
          - "node.label==rabbitmq"
          # - "engine.labels.operatingsystem==ubuntu 18.04"
        # max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - rabbitmq
# healthcheck:
#   test: ["CMD", "curl", "-f", "http://localhost"]
#   interval: 1m30s
#   timeout: 10s
#   retries: 3
#   start_period: 40s


networks:
  rabbitmq:
    external: true
    name: rabbitmq

