# Build Orgin Container | Used by CI Container (GitLabRunner) | /srv/data/dockerfile/Dockerfile-ms_place_mgm
FROM python:3.8-slim-bullseye
MAINTAINER MohammadReza Izadi <mohammadreza.i1997@gmail.com>
##################################### Set Local Repo  ###################################
RUN echo "deb http://192.168.7.250:8082/artifactory/debian-remote bullseye main\ndeb http://192.168.7.250:8082/artifactory/debian-remote bullseye-updates main" > /etc/apt/sources.list
#########################################################################################
WORKDIR /opt
COPY . .
RUN \
  apt update && \
  apt install -y libgdal-dev gdal-bin make build-essential libsqlite3-dev zlib1g-dev \
  && cd tippecanoe \
  && make -j \
  &&  make install \
  && rm -rf /var/lib/apt/lists/*